export const cities = [
  "Abohar", "Abu Road", "Achalpur", "Adilabad", "Adoni", "Agar", "Agartala", "Agra", "Ahmedabad", "Ahmednagar",
  "Aizawl", "Ajmer", "Akbarpur", "Akola", "Akot", "Aland", "Alappuzha", "Aligarh", "Alipurduar", "Alirajpur",
  "Allahabad", "Almora", "Alwar", "Amalapuram", "Amalner", "Ambah", "Ambala", "Ambasamudram", "Ambattur", "Ambejogai",
  "Ambernath", "Ambur", "Amravati", "Amreli", "Amritsar", "Amroha", "Anakapalle", "Anand", "Anandpur Sahib", "Anantapur",
  "Anjangaon", "Anjar", "Ankleshwar", "Anuppur", "Arakkonam", "Arambagh", "Arani", "Arrah", "Aruppukkottai", "Asansol",
  "Ashoknagar", "Ashtamichira", "Attur", "Aurangabad", "Avadi", "Baddi", "Badin", "Badlapur", "Baduria", "Bagaha",
  "Bageshwar", "Bagpat", "Bahadurgarh", "Baharampur", "Baheri", "Bahraich", "Bajpur", "Balaghat", "Balangir", "Balasore",
  "Baleshwar", "Ballarpur", "Ballia", "Bally", "Balotra", "Balrampur", "Banda", "Bandikui", "Bangalore", "Banganapalle",
  "Bankura", "Bansberia", "Banswara", "Bapatla", "Baramati", "Baramula", "Baran", "Baranagar", "Barasat", "Baraut",
  "Bardhaman", "Bareilly", "Bargarh", "Baripada", "Barmer", "Barnala", "Barpeta", "Barshi", "Barwani", "Basirhat",
  "Basoda", "Basti", "Batala", "Bathinda", "Bawan", "Bawana", "Beawar", "Begusarai", "Belgaum", "Bellary",
  "Berhampur", "Bettiah", "Betul", "Bhadohi", "Bhadrak", "Bhadravati", "Bhadreswar", "Bhadu", "Bhagalpur", "Bhalswa Jahangir Pur",
  "Bhalukpong", "Bhandara", "Bharatpur", "Bharuch", "Bhatpara", "Bhavani", "Bhavnagar", "Bhawanipatna", "Bhayandar", "Bhilai",
  "Bhilwara", "Bhimavaram", "Bhind", "Bhinmal", "Bhiwadi", "Bhiwandi", "Bhiwani", "Bhongir", "Bhopal", "Bhor",
  "Bhubaneswar", "Bhuj", "Bhusawal", "Biaora", "Bida", "Bidar", "Bidhannagar", "Bihar Sharif", "Bijapur", "Bijnor",
  "Bikaner", "Bilara", "Bilasipara", "Bilaspur", "Bishnupur", "Bobbili", "Bodhan", "Boisar", "Bokaro", "Bongaigaon",
  "Bongaon", "Brahmapur", "Budaun", "Budge Budge", "Bulandshahr", "Buldhana", "Bundi", "Burhanpur", "Buxar", "Byasanagar",
  "Cambay", "Chakdaha", "Chalisgaon", "Challakere", "Chandausi", "Chandigarh", "Chandrapur", "Chapra", "Charkhi Dadri", "Chengannur",
  "Chennai", "Chhatarpur", "Chhindwara", "Chidambaram", "Chikhli", "Chikmagalur", "Chiknayakanhalli", "Chilakaluripet", "Chinchwad", "Chinsurah",
  "Chirala", "Chirmiri", "Chitradurga", "Chittoor", "Chittorgarh", "Chittur-Thathamangalam", "Chopan", "Chopda", "Chotila", "Churu",
  "Coimbatore", "Cuddalore", "Cumbum", "Cuttack", "Dabra", "Dadri", "Dahanu", "Dahod", "Daltonganj", "Damoh",
  "Danapur", "Darbhanga", "Darjeeling", "Datia", "Daund", "Dausa", "Davanagere", "Davangere", "Deesa", "Dehradun",
  "Dehri", "Delhi", "Deoghar", "Deoria", "Deulgaon Raja", "Dewas", "Dhamtari", "Dhanbad", "Dhar", "Dharampur",
  "Dharamsala", "Dharapuram", "Dharmavaram", "Dharwad", "Dhenkanal", "Dholka", "Dholpur", "Dhule", "Dhuri", "Dibrugarh",
  "Dimapur", "Dindigul", "Dindori", "Diphu", "Dombivli", "Dondaicha", "Dumdum", "Dumka", "Dungarpur", "Durg",
  "Durgapur", "Eluru", "English Bazar", "Erode", "Etah", "Etawah", "Faridabad", "Faridkot", "Farrukhabad", "Fatehabad",
  "Fatehpur", "Fazilka", "Firozabad", "Firozpur", "Forbesganj", "Gadag-Betageri", "Gadchiroli", "Gadwal", "Gandhidham", "Gandhinagar",
  "Gangapur", "Gangarampur", "Gangavathi", "Gangtok", "Ganjam", "Garhwa", "Gauripur", "Gaya", "Ghatal", "Ghatampur",
  "Ghaziabad", "Ghazipur", "Giridih", "Goa Velha", "Goalpara", "Gobichettipalayam", "Gobindgarh", "Godda", "Godhra", "Gohana",
  "Gokak", "Golaghat", "Gomoh", "Gondia", "Gondiya", "Gooty", "Gopalganj", "Gopalpur", "Gorakhpur", "Greater Noida",
  "Gudivada", "Gudur", "Gulbarga", "Gumia", "Guna", "Guntakal", "Guntur", "Gurdaspur", "Gurgaon", "Guruvayoor",
  "Guwahati", "Gwalior", "Habra", "Haflong", "Hajipur", "Haldia", "Haldwani", "Hamirpur", "Hansi", "Hanumangarh",
  "Hapur", "Harda", "Hardoi", "Haridwar", "Harsawa", "Harsud", "Hassan", "Hastinapur", "Hathras", "Hazaribag",
  "Hazaribagh", "Hilsa", "Himatnagar", "Hindupur", "Hinganghat", "Hingoli", "Hisar", "Hojai", "Hoshangabad", "Hoshiarpur",
  "Hospet", "Hosur", "Howrah", "Hubli", "Hubli-Dharwad", "Hugli", "Hugli And Chinsurah", "Hunsur", "Hussainabad", "Hyderabad",
  "Ichalkaranji", "Igatpuri", "Ilkal", "Imphal", "Indapur", "Indore", "Indragarh", "Irinjalakuda", "Islampur", "Itanagar",
  "Itarsi", "Jabalpur", "Jagdalpur", "Jaggaiahpet", "Jagraon", "Jagtial", "Jahanabad", "Jaipur", "Jais", "Jaisalmer",
  "Jaitu", "Jajapur", "Jajmau", "Jalalabad", "Jalalpore", "Jalandhar", "Jaleswar", "Jalgaon", "Jalgaon Jamod", "Jalna",
  "Jalor", "Jalore", "Jalpaiguri", "Jamalpur", "Jammalamadugu", "Jammu", "Jamnagar", "Jamshedpur", "Jamtara", "Jamui",
  "Jandiala", "Jangaon", "Jangipur", "Janjgir", "Jashpurnagar", "Jaspur", "Jaunpur", "Jehanabad", "Jhabua", "Jhajjar",
  "Jhalawar", "Jhansi", "Jhargram", "Jharsuguda", "Jhumri Tilaiya", "Jhunjhunu", "Jind", "Joda", "Jodhpur", "Jorhat",
  "Junagadh", "Kadapa", "Kadi", "Kadiri", "Kagaznagar", "Kailasahar", "Kaithal", "Kakching", "Kakinada", "Kalyan",
  "Kalyan-Dombivli", "Kalyani", "Kamareddy", "Kamarhati", "Kanchipuram", "Kandukur", "Kangra", "Kanhangad", "Kanjikkuzhi", "Kanker",
  "Kannur", "Kanpur", "Kantabanji", "Kapadvanj", "Kapurthala", "Karad", "Karaikal", "Karaikudi", "Karanja", "Karanjia",
  "Karawal Nagar", "Karimganj", "Karimnagar", "Karjat", "Karnal", "Karsiyang", "Karur", "Karwar", "Kasaragod", "Kashipur",
  "Kathua", "Katihar", "Kavali", "Kavaratti", "Kayamkulam", "Kendrapara", "Kendujhar", "Keshod", "Khagaria", "Khambhat",
  "Khamgaon", "Khammam", "Khandwa", "Khanna", "Kharagpur", "Kharar", "Khargone", "Kheri", "Khopoli", "Khora",
  "Khurda", "Kirari Suleman Nagar", "Kishanganj", "Kishangarh", "Kochi", "Kodungallur", "Kohima", "Kokrajhar", "Kolar", "Kolhapur",
  "Kolkata", "Kollam", "Kondagaon", "Konnagar", "Koothuparamba", "Koraput", "Koratla", "Korba", "Kot Kapura", "Kota",
  "Kothagudem", "Kothamangalam", "Kottayam", "Kovvur", "Kozhikode", "Krishnanagar", "Kuchaman", "Kulgam", "Kullu", "Kulti",
  "Kumbakonam", "Kumta", "Kundapura", "Kunnamkulam", "Kurali", "Kurnool", "Kyathampalle", "Lachung", "Ladnu", "Ladwa",
  "Lahar", "Laharpur", "Lakheri", "Lakhimpur", "Lakhisarai", "Lakshmeshwar", "Lal Gopalganj Nindaura", "Lalganj", "Lalgudi", "Lalitpur",
  "Lalsot", "Lanka", "Lar", "Lathi", "Latur", "Lilong", "Limbdi", "Lingsugur", "Loha", "Lohardaga",
  "Lonar", "Lonavala", "Lonavla", "Longowal", "Loni", "Losal", "Lucknow", "Ludhiana", "Lumding", "Lunawada",
  "Lunglei", "Macherla", "Machilipatnam", "Madanapalle", "Maddur", "Madhepura", "Madhubani", "Madhugiri", "Madhupur", "Madhyamgram",
  "Madikeri", "Madurai", "Magadi", "Mahabaleshwar", "Mahad", "Mahalingapura", "Maharajganj", "Maharajpur", "Mahasamund", "Mahbubnagar",
  "Mahe", "Mahemdabad", "Mahendragarh", "Mahesana", "Maheshtala", "Mahidpur", "Mahnar Bazar", "Mahuva", "Maihar", "Mainaguri",
  "Makhdumpur", "Makrana", "Mal", "Malaj Khand", "Malappuram", "Malavalli", "Malda", "Malegaon", "Malerkotla", "Malkangiri",
  "Malkapur", "Malout", "Malpura", "Malur", "Manachanallur", "Manasa", "Manavadar", "Manawar", "Mancherial", "Mandalgarh",
  "Mandamarri", "Mandapeta", "Mandawa", "Mandi", "Mandi Dabwali", "Mandideep", "Mandla", "Mandsaur", "Mandvi", "Mandya",
  "Manendragarh", "Maner", "Mangaldoi", "Mangalore", "Mangaluru", "Mangalvedhe", "Manglaur", "Mango", "Mangrol", "Mangrulpir",
  "Manihari", "Manjeri", "Manjlegaon", "Mankachar", "Manmad", "Mansa", "Manuguru", "Manvi", "Manwath", "Mapusa",
  "Margao", "Margherita", "Marhaura", "Mariani", "Marigaon", "Markapur", "Marmagao", "Masaurhi", "Mathabhanga", "Mathura",
  "Mattannur", "Mau", "Mauganj", "Mavelikkara", "Mavoor", "Mayang Imphal", "Medak", "Medininagar", "Medinipur", "Meerut",
  "Mehemdabad", "Mehkar", "Memari", "Merta City", "Mhaswad", "Mhow", "Mhow Cantonment", "Mhowgaon", "Midnapore", "Mihijam",
  "Mira Road", "Mira-Bhayandar", "Miraj", "Mirganj", "Miryalaguda", "Mirzapur", "Modasa", "Modinagar", "Moga", "Mohali",
  "Mokameh", "Mokokchung", "Monoharpur", "Moradabad", "Morena", "Morinda", "Mormugao", "Morshi", "Morvi", "Motala",
  "Motihari", "Motipur", "Mount Abu", "Mudabidri", "Mudalagi", "Muddebihal", "Mudhol", "Mukerian", "Mukhed", "Muktsar",
  "Mul", "Mulbagal", "Multai", "Mumbai", "Mundargi", "Mundi", "Mungeli", "Munger", "Muradnagar", "Murbad",
  "Murshidabad", "Murtizapur", "Murwara", "Musabani", "Mussoorie", "Muvattupuzha", "Muzaffarnagar", "Muzaffarpur", "Mysore", "Nabadwip",
  "Nabarangapur", "Nabha", "Nadbai", "Nadiad", "Nagaon", "Nagapattinam", "Nagar", "Nagari", "Nagarkurnool", "Nagaur",
  "Nagda", "Nagercoil", "Nagina", "Nagla", "Nagpur", "Nahan", "Naharlagun", "Naidupet", "Naihati", "Naila Janjgir",
  "Nainital", "Nainpur", "Najibabad", "Nakodar", "Naksalbari", "Nala Sopara", "Nalbari", "Nalgonda", "Namagiripettai", "Namakkal",
  "Nanded", "Nanded-Waghala", "Nandgaon", "Nandivaram-Guduvancheri", "Nandura", "Nandurbar", "Nandyal", "Nangal", "Nangloi Jat", "Nanjangud",
  "Nanjikottai", "Nanpara", "Narasapur", "Narasaraopet", "Naraura", "Narayanpet", "Nargund", "Narkatiaganj", "Narkhed", "Narnaul",
  "Narsinghgarh", "Narsinghpur", "Narsipatnam", "Narwana", "Nashik", "Nasirabad", "Natham", "Nathdwara", "Naugachhia", "Navalgund",
  "Navghar", "Navi Mumbai", "Navsari", "Nawabganj", "Nawada", "Nawanshahr", "Nawapur", "Nedumangad", "Neem-Ka-Thana", "Neemuch",
  "Nehtaur", "Nelamangala", "Nellikuppam", "Nellore", "Nepanagar", "New Delhi", "Neyveli", "Neyyattinkara", "Nidadavole", "Nilambur",
  "Nilanga", "Nimbahera", "Nirmal", "Niwari", "Nizamabad", "Nohar", "Noida", "Nokha", "Nongstoin", "Noorpur",
  "North Dumdum", "North Lakhimpur", "Nowgong", "Nowrozabad", "Nuzvid", "Obra", "Oddanchatram", "Ongole", "Ooty", "Orai",
  "Osmanabad", "Ottappalam", "Ozar", "Ozhukarai", "Pachora", "Pachore", "Pacode", "Padmanabhapuram", "Padra", "Padrauna",
  "Paithan", "Pakaur", "Palacole", "Palai", "Palakkad", "Palampur", "Palani", "Palanpur", "Palasa Kasibugga", "Palghar",
  "Pali", "Palia Kalan", "Palitana", "Palladam", "Pallapatti", "Pallavaram", "Pallikonda", "Palwal", "Palwancha", "Panagar",
  "Panagudi", "Panaji", "Panamattom", "Panchkula", "Panchla", "Pandharkaoda", "Pandharpur", "Pandhurna", "Pandua", "Panihati",
  "Panipat", "Panna", "Panniyannur", "Panruti", "Panvel", "Pappinisseri", "Paradip", "Paramakudi", "Parangipettai", "Parasi",
  "Paravoor", "Parbhani", "Pardi", "Parlakhemundi", "Parli", "Partur", "Parvathipuram", "Pasan", "Paschim Punropara", "Pasighat",
  "Patan", "Pathanamthitta", "Pathankot", "Pathardi", "Pathri", "Patiala", "Patna", "Patratu", "Pattamundai", "Patti",
  "Pattran", "Pattukkottai", "Patur", "Pauni", "Pauri", "Pavagada", "Pedana", "Peddapuram", "Pehowa", "Pen",
  "Perambalur", "Peravurani", "Peringathur", "Perinthalmanna", "Periyakulam", "Periyasemur", "Pernampattu", "Perumbavoor", "Petlad", "Phagwara",
  "Phalodi", "Phaltan", "Phillaur", "Phulabani", "Phulera", "Phulpur", "Phusro", "Pihani", "Pilani", "Pilibanga",
  "Pilibhit", "Pilkhuwa", "Pimpri", "Pimpri-Chinchwad", "Pindwara", "Pinjore", "Pipar City", "Pipariya", "Piro", "Pithampur",
  "Pithapuram", "Pithoragarh", "Pokhran", "Pollachi", "Polur", "Pondicherry", "Ponnani", "Ponneri", "Ponnur", "Porbandar",
  "Porsa", "Port Blair", "Powayan", "Prantij", "Pratapgarh", "Prithvipur", "Proddatur", "Puducherry", "Pudukkottai", "Pudupattinam",
  "Pukhrayan", "Pulgaon", "Puliyankudi", "Punalur", "Punch", "Pune", "Punganur", "Punjaipugalur", "Puranpur", "Puri",
  "Purna", "Purnia", "Purqazi", "Purulia", "Puruliya", "Purwa", "Pusad", "Puttur", "Putu", "Qadian",
  "Quilandy", "Rabkavi Banhatti", "Radhanpur", "Rae Bareli", "Rafiganj", "Raghogarh", "Raghogarh-Vijaypur", "Raghunathpur", "Rahatgarh", "Rahuri",
  "Raichur", "Raiganj", "Raigarh", "Raikot", "Raipur", "Rairangpur", "Raisen", "Raisinghnagar", "Rajagangapur", "Rajahmundry",
  "Rajakhera", "Rajaldesar", "Rajam", "Rajampet", "Rajapalayam", "Rajauri", "Rajgarh", "Rajgir", "Rajkot", "Rajnandgaon",
  "Rajpipla", "Rajpura", "Rajsamand", "Rajula", "Rajura", "Ramachandrapuram", "Ramagundam", "Ramanagaram", "Ramanathapuram", "Ramdurg",
  "Rameshwaram", "Ramganj Mandi", "Ramgarh", "Ramnagar", "Ramngarh", "Rampur", "Rampur Maniharan", "Rampurhat", "Ramura", "Ranaghat"
];


export const getCitySlug = (city: string): string => {
  return city
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)+/g, "");
};

export const getCitySlugsList = (): string[] => {
  return cities.map(getCitySlug);
};
